declare module "*Home"
declare module "*Signin"
declare module "*SignUp"
declare module "*Profile"
declare module "*About"
declare module "*Header"
declare module "*store.js"
declare module "*redux-persist/integration/react"
// declare module "*react-slick"